const LOGOUT = 'LOGOUT';
const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
const SIGNIN_RESPONSE = 'SIGNIN_RESPONSE';
const AUTH_ERROR = 'AUTH_ERROR';
export {
  LOGOUT,
  SIGNIN_REQUEST,
  SIGNIN_RESPONSE,
  SIGNUP_REQUEST,
  AUTH_ERROR
}
