const LOGOUT = 'LOGOUT';
const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
const SIGNIN_RESPONSE = 'SIGNIN_RESPONSE';
const SIGNIN_ERROR = 'SIGNIN_ERROR';
const SIGNUP_ERROR = 'SIGNUP_ERROR';
export {
  LOGOUT,
  SIGNIN_REQUEST,
  SIGNIN_RESPONSE,
  SIGNUP_REQUEST,
  SIGNIN_ERROR,
  SIGNUP_ERROR,
}
