const CREATE_POLL_REQUEST = 'CREATE_POLL_REQUEST';
const CREATE_POLL_RESPONSE = 'CREATE_POLL_RESPONSE';
const ANSWER_POLL_REQUEST = 'ANSWER_POLL_REQUEST';
const GET_POLL_REQUEST = 'GET_POLL_REQUEST';
const GET_POLL_RESPONSE = 'GET_POLL_RESPONSE';
const GET_POLL_ERROR = 'GET_POLL_ERROR';
const GET_ALL_POLLS_REQUEST = 'GET_ALL_POLLS_REQUEST';
const GET_ALL_POLLS_RESPONSE = 'GET_ALL_POLLS_RESPONSE';
const GET_MY_POLLS_REQUEST = 'GET_MY_POLLS_REQUEST';
const GET_MY_POLLS_RESPONSE = 'GET_MY_POLLS_RESPONSE';
const GET_LEADERBOARD_REQUEST = 'GET_LEADERBOARD_REQUEST';
const GET_LEADERBOARD_RESPONSE = 'GET_LEADERBOARD_RESPONSE';
const FILTER_POLLS = 'FILTER_POLLS';
const CLEAR_POLL_INPUTS = 'CLEAR_POLL_INPUTS';
const UPDATE_POLL_INPUT = 'UPDATE_POLL_INPUT';
const CLEAR_POLL_DATA = 'CLEAR_POLL_DATA';

export {
  CLEAR_POLL_DATA,
  CLEAR_POLL_INPUTS,
  UPDATE_POLL_INPUT,
  ANSWER_POLL_REQUEST,
  CREATE_POLL_REQUEST,
  CREATE_POLL_RESPONSE,
  GET_MY_POLLS_REQUEST,
  GET_MY_POLLS_RESPONSE,
  GET_LEADERBOARD_REQUEST,
  GET_LEADERBOARD_RESPONSE,
  GET_ALL_POLLS_REQUEST,
  GET_ALL_POLLS_RESPONSE,
  GET_POLL_REQUEST,
  GET_POLL_ERROR,
  GET_POLL_RESPONSE,
  FILTER_POLLS,
}

