const SET_LOADING_STATE = 'SET_LOADING_STATE';
const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
const UPLOAD_IMAGE_RESPONSE = 'UPLOAD_IMAGE_RESPONSE';
const SAVE_INFO_REQUEST = 'SAVE_INFO_REQUEST';
const SAVE_INFO_RESPONSE = 'SAVE_INFO_RESPONSE';
const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
const CHANGE_PASSWORD_RESPONSE = 'CHANGE_PASSWORD_RESPONSE';
export {
  CHANGE_PASSWORD_REQUEST,
  CHANGE_PASSWORD_RESPONSE,
  SAVE_INFO_REQUEST,
  SAVE_INFO_RESPONSE,
  SET_LOADING_STATE,
  UPLOAD_IMAGE_REQUEST,
  UPLOAD_IMAGE_RESPONSE
}
